"""add threads

Revision ID: 24588024f6d8
Revises: 5e2867f92124
Create Date: 2026-08-20 14:09:13.130036

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "24588024f6d8"
down_revision: str | None = "5e2867f92124"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "threads",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("employee_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_foreign_key(
        "fk_department_head",
        "departments",
        "employees",
        ["head_id"],
        ["id"],
        use_alter=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_department_head", "departments", type_="foreignkey")
    op.drop_table("threads")
    # ### end Alembic commands ###
